/*
 * Copyright (C) 2024 Volt Active Data Inc.
 *
 * Use of this source code is governed by an MIT
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */

@Library('voltdb') _
def defaultRelease = false
if (BRANCH_NAME == "main") {
    defaultRelease = true
}

pipeline {
    agent {
       label 'gcloud-build--rocky-linux-8--x64'
    }
    // We use java 8 for this.
    // environment {               
       // JAVA_HOME = "/opt/corretto_java17"  
    // }  
    stages {
        stage('Set version') {
            steps {
                script {
                    startedStage('Set version')
                }

                script {
                    sh 'mvn versions:set -DnewVersion=1.0.1-SNAPSHOT -ntp'
                }
            }
            post {
                success {
                    successfulStage('Set version')
                }
                failure {
                    failedStage('Set version')
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    startedStage('Tests')
                }
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_CREDS_USR', passwordVariable: 'DOCKER_CREDS_PSW')]) {
                        sh '''
                            echo "login to docker..."
                            echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin docker.io
                            echo "building..."
                        '''
                    }

                    withCredentials([string(credentialsId: 'VOLTDB_LICENSE', variable: 'LICENSE')]) {
                        writeFile file: "/tmp/voltdb-license.xml", text: "$LICENSE", encoding: "UTF-8"
                    }

                    sh '''
                       mvn clean install javadoc:javadoc
                    '''
                }
            }
            post {
                success {
                    successfulStage('Tests')
                }
                unsuccessful {
                    failedStage('Tests')
                }
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Publish') {
            when {
                expression { defaultRelease }
            }
            steps {
                script {
                    startedStage('Publish')
                }
                script {
                    withCredentials([file(credentialsId: 'maven-repos-dev-write', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                        sh """#!/bin/bash
                            mvn deploy -ntp -DskipTests
                        """
                    }
                }
            }
            post {
                success {
                    successfulStage('Publish')
                }
                failure {
                    failedStage('Publish')
                }
            }
        }
    }
}
